version: "3.9"

services:
  mysql:
    image: mysql
    container_name: mysql
    restart: on-failure
    ports:
      - 3307:3306
    volumes:
      - mysql-db:/var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD: "root1234"
      MYSQL_DATABASE: "pizza_kitchen"
      MYSQL_PASSWORD: "root1234"
    networks:
      - kitchen-network
  api:
    build: .
    container_name: kitchen_api
    restart: on-failure
    networks:
      - kitchen-network
    ports:
      - 8083:8082
    depends_on:
      - mysql
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  kitchen-network:
    driver: bridge

volumes:
  mysql-db:
